server:
  port: 8123
  address: 0.0.0.0  # 绑定到所有网络接口，允许局域网访问
  servlet:
    context-path: /api
spring:
  application:
    name: lockdemo
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lockdemo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: yzt12280
mybatis-plus:
  # mapper XML 文件路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true  # 启用驼峰命名转换，将实体类的驼峰字段名自动转换为数据库的下划线字段名
    # 仅在开发环境开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "智能锁接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - cn.iocoder.cloud.lockdemo.controller
